services:
    server:
        image: elemem/vpu_engine:v2.0.0.1
        container_name: vpu_engine
        privileged: true
        volumes:
            - /dev:/dev
        ports:
          - "8008:8000"
        restart: unless-stopped

    client:
        image: elemem/client_demo:v0.2
        container_name: client_demo
        depends_on:
            - server
        networks:
            - hilnet
networks:
    hilnet:
        driver: bridge
